config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'rooms/index'

  resources :rooms, only: [:create, :show], param: :title
  resources :messages, only: :create
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    delete '/logout', to: 'devise/sessions#destroy'
  end

  get 'friends/show'

  get 'users/:id', to: 'users#show', as: :user_profile

  root 'home#show'

  resources :friendships, only: [:create, :update, :destroy] do
    member do
      patch :accept
      patch :reject
    end
  end

  resource :user, only: [:edit, :update]

  get 'friendship_status', to: 'friendships#show', as: :friendship_status
  get 'friends', to: 'friends#show', as: :friend
  get 'friend_show', to: 'friends#index', as: :friend_show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :requested, class_name: 'User'

  scope :pending_requests_for, ->(user) { where(requested_id: user.id, status: 'pending') }

  def create_room_for_friendship(user_id1, user_id2)
    room = Room.create(user_id: user_id1, title: "Room_#{SecureRandom.hex(3)}")
    room.users << [User.find(user_id1), User.find(user_id2)]
  end
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message, counter_cache: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  scope :sorted, ->  { order(:id)}

  validates :body, presence: true, unless: :image_attached?

  mount_uploader :image, ImageUploader

  def image_attached?
    self.image.present? && self.image.file.present?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, -> { sorted }, dependent: :destroy
  belongs_to :user
  before_create {self.title = SecureRandom.hex(3)}
  has_many :rooms_users
  has_many :users, through: :rooms_users
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requested_friendships, foreign_key: :requester_id, class_name: 'Friendship'
  has_many :received_friendships, foreign_key: :requested_id, class_name: 'Friendship'
  has_many :requested_friends, through: :requested_friendships, source: :requested
  has_many :received_friends, through: :received_friendships, source: :requester
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :rooms

  before_validation :set_default_name, on: :create

  validates :name, presence: true

  mount_uploader :avatar, AvatarUploader

  def pending_friend_requests
    Friendship.where(requested_id: id, status: 'pending')
  end

  def friends
    received_friends.where(friendships: { status: 'accepted' })
  end

  private

  def set_default_name
    self.name ||= "User-#{SecureRandom.hex(3)}"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def show
    @friend_requests = Friendship.pending_requests_for(current_user)
  end

  def index

  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def show
    @users = User.where.not(id: current_user.id)
    @current_user = current_user
  end

  def index
    @users = User.where.not(id: current_user.id)
    @current_user = current_user
  end

  def create
    requested_user = User.find(params[:friendship][:requested_id])

    if current_user.friends.include?(requested_user)
      flash[:alert] = 'Этот пользователь уже ваш друг'
      redirect_back fallback_location: root_path
    elsif current_user.pending_friend_requests.exists?(requested_id: requested_user.id)
      flash[:alert] = 'Запрос на дружбу уже был отправлен'
      redirect_back fallback_location: root_path
    else
      @friendship = Friendship.new(requester_id: current_user.id, requested_id: requested_user.id, status: 'pending', sent_request: true)

      if @friendship.save
        flash[:notice] = 'Запрос на дружбу отправлен'
      else
        flash[:alert] = 'Не удалось отправить запрос на дружбу'
      end

      redirect_back fallback_location: root_path
    end
  end

  def accept
    @friendship = Friendship.find_by(id: params[:id], requested_id: current_user.id, status: 'pending')

    if @friendship
      if @friendship.status == 'pending'
        Friendship.transaction do
          @friendship.update(status: 'accepted')

          # Отменяем все остальные запросы от этого пользователя,
          # которые имеют статус 'pending'
          Friendship.where(requester_id: @friendship.requester_id, requested_id: @friendship.requested_id, status: 'pending')
                    .where.not(id: @friendship.id)
                    .update_all(status: 'rejected')

          @friendship.create_room_for_friendship(@friendship.requester_id, @friendship.requested_id)

          reverse_friendship = Friendship.create(requester_id: @friendship.requested_id, requested_id: @friendship.requester_id, status: 'accepted')
          flash[:notice] = 'Запрос на дружбу принят'
        end
      else
        flash[:alert] = 'Запрос на дружбу уже принят'
      end
    else
      flash[:alert] = 'Невозможно принять запрос на дружбу'
    end

    redirect_back fallback_location: root_path
  end

  def reject
    @friendship = Friendship.find_by(id: params[:id], requested_id: current_user.id)

    if @friendship && @friendship.status == 'pending'
      @friendship.update(status: 'rejected')
      flash[:notice] = 'Запрос на дружбу отклонен'
    else
      flash[:alert] = 'Невозможно отклонить запрос на дружбу'
    end

    redirect_back fallback_location: root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @rooms = Room.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @new_message = current_user.messages.build(strong_params)
    if @new_message.save
      @new_message.broadcast_append_to @new_message.room
    end
  end

  private

  def strong_params
    params.require(:message).permit(:room_id, :body, :image)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @new_room = Room.new
    @rooms = Room.all
  end

  def create
    @new_room = current_user&.rooms&.build
    if @new_room&.save
      @new_room.broadcast_append_to :rooms
    end
  end

  def show
    @room = Room.find_by!(title: params[:title])
    @messages = @room.messages
    @new_message = current_user&.messages&.build
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_user_path(@user), notice: 'Профиль успешно обновлен.'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :descriptions, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_link(title)
    request.protocol + request.host_with_port + "/rooms/#{title}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/index.html.erb
<div class="content-wrapper buffer-both text-center">

  <button type="button" class="btn btn-dark btn-lg butt"><a href="friends" style="text-decoration: none; color: inherit;">Запросы</a></button>
  <button type="button" class="btn btn-dark btn-lg butt"><a href="friend_show" style="text-decoration: none; color: inherit;">Друзья</a></button>


  <div class="buffer-both">
    <h1 class="title-medium">Ваши друзья</h1>
    <div class="user-avatars-container" style="display: flex; flex-wrap: wrap; justify-content: center;">
      <% current_user.friends.each do |friend| %>
        <div class="users-list-item">
          <div class="user-image-div user-image-div-small" style="margin: 10px;">
            <% if friend.avatar? %>
              <%= image_tag friend.avatar.thumb.url, alt: "#{friend.name}'s аватар", class: "rounded-avatar" %>
            <% else %>
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCSiylwVA6PW_GnlrPL-UmN7zPcmtnzPqXSVExvXbpPQ&s" alt="заглушка" class="rounded-avatar" height="100px" width="100px">
            <% end %>
            <p><%= friend.name %></p>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/friends/show.html.erb
<div class="content-wrapper buffer-both text-center">

  <button type="button" class="btn btn-dark btn-lg butt"><a href="friends" style="text-decoration: none; color: inherit;">Запросы</a></button>
  <button type="button" class="btn btn-dark btn-lg butt"><a href="friend_show" style="text-decoration: none; color: inherit;">Друзья</a></button>

  <div class="buffer-both">
    <h1 class="title-medium">Запросы на дружбу</h1>
  </div>

<% if @friend_requests.any? %>
  <ul>
    <% @friend_requests.each do |friend_request| %>
      <li>
        <%= "Предложил: #{friend_request.requester.name}" %>
        <%= button_to 'Принять', accept_friendship_path(friend_request), method: :patch, remote: true, class: 'accept-friendship-link btn btn-success', data: { friendship_id: friend_request.id } %>
        <%= button_to 'Отклонить', reject_friendship_path(friend_request), method: :patch, remote: true, class: 'reject-friendship-link btn btn-danger', data: { friendship_id: friend_request.id } %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Нету запросов на дружбу</p>
<% end %>

</div>

app/views/friendships/show.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>
  <div class="user-avatars-container" style="display: flex; flex-wrap: wrap; justify-content: center;">
    <% @users.each do |user| %>
      <% next if user == current_user %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small" style="margin: 10px;">
          <% if user.avatar? %>
            <%= image_tag user.avatar.thumb.url, alt: "#{user.name}'s аватар", class: "rounded-avatar" %>
          <% else %>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCSiylwVA6PW_GnlrPL-UmN7zPcmtnzPqXSVExvXbpPQ&s" alt="заглушка" class="rounded-avatar" height="100px" width="100px">
          <% end %>
          <p><%= user.name %></p>

          <% if current_user.friends.include?(user) %>
            <button type="button" class="btn btn-dark">Вы уже друзья</button>
          <% elsif current_user.pending_friend_requests.exists?(requested_id: user.id) %>
            <button type="button" class="btn btn-dark" disabled>Запрос отправлен</button>
          <% else %>
            <% requested_friendship = current_user.requested_friendships.find_by(requested_id: user.id) %>
            <% if requested_friendship.present? %>
              <% if requested_friendship.status == 'accepted' %>
                <button type="button" class="btn btn-dark">Вы уже друзья</button>
              <% elsif requested_friendship.status == 'rejected' %>
                <%= form_with(model: Friendship.new, url: friendships_path, method: :post, class: 'friendship-form') do |form| %>
                  <%= form.hidden_field :requested_id, value: user.id %>
                  <%= form.submit 'Добавить в друзья', class: 'btn btn-dark' %>
                <% end %>
              <% elsif current_user.pending_friend_requests.exists?(requested_id: user.id) %>
                <button type="button" class="btn btn-dark" disabled>Запрос отправлен</button>
              <% end %>
            <% else %>
              <%= form_with(model: Friendship.new, url: friendships_path, method: :post, class: 'friendship-form') do |form| %>
                <%= form.hidden_field :requested_id, value: user.id %>
                <%= form.submit current_user.pending_friend_requests.exists?(requested_id: user.id) ? 'Запрос отправлен' : 'Добавить в друзья', class: 'btn btn-dark' %>
              <% end %>
            <% end %>
          <% end %>

        </div>
      </div>
    <% end %>
  </div>
</div>


<script>

    document.addEventListener('DOMContentLoaded', () => {
        const friendshipForms = document.querySelectorAll('.friendship-form');

        friendshipForms.forEach(form => {
            form.addEventListener('submit', async (event) => {
                event.preventDefault();

                // Найти кнопку отправки внутри формы
                const submitButton = form.querySelector('input[type="submit"]');

                // Проверить, заблокирована ли кнопка
                if (submitButton.disabled) {
                    return; // Если кнопка заблокирована, не выполнять дальнейшие действия
                }

                try {
                    // Заблокировать кнопку перед отправкой запроса
                    submitButton.disabled = true;

                    const response = await fetch(form.action, {
                        method: form.method,
                        body: new FormData(form),
                        headers: {
                            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
                        }
                    });

                    if (response.ok) {
                        // Изменить текст и заблокировать кнопку после успешной отправки запроса на дружбу
                        submitButton.value = 'Запрос отправлен';
                        submitButton.disabled = true;
                    } else {
                        // Разблокировать кнопку в случае ошибки при отправке запроса
                        submitButton.disabled = false;
                        console.error('Ошибка при отправке запроса на сервер');
                    }
                } catch (error) {
                    // Разблокировать кнопку в случае ошибки соединения
                    submitButton.disabled = false;
                    console.error(error);
                }
            });
        });
    });

    document.addEventListener('DOMContentLoaded', () => {
        const acceptLinks = document.querySelectorAll('.accept-friendship-link');
        const rejectLinks = document.querySelectorAll('.reject-friendship-link');

        acceptLinks.forEach(link => {
            link.addEventListener('click', async (e) => {
                e.preventDefault();

                const friendshipId = link.dataset.friendshipId;
                const url = `/friendships/${friendshipId}/accept`;

                try {
                    const response = await fetch(url, {
                        method: 'PATCH',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
                        }
                    });

                    // Обработка ответа...
                } catch (error) {
                    console.error(error);
                }
            });
        });

        rejectLinks.forEach(link => {
            link.addEventListener('click', async (e) => {
                e.preventDefault();

                const friendshipId = link.dataset.friendshipId;
                const url = `/friendships/${friendshipId}/reject`;

                try {
                    const response = await fetch(url, {
                        method: 'PATCH',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
                        }
                    });

                    // Обработка ответа...
                } catch (error) {
                    console.error(error);
                }
            });
        });
    });

</script>

app/views/home/show.html.erb
<% if current_user %>
<!DOCTYPE html>
  <html>
  <body>

  <div class="chat-list">
    <% if current_user.friends.any? %>
      <% current_user.friends.each do |friend| %>
        <% friend.rooms.each do |room| %>
          <% if room.users.include?(current_user) %>
            <div class="chat">
              <% if friend.avatar? %>
                <img src="<%= friend.avatar_url %>" alt="<%= friend.name %>" class="rounded-avatar" height="100px" width="100px">
              <% else %>
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCSiylwVA6PW_GnlrPL-UmN7zPcmtnzPqXSVExvXbpPQ&s" alt="заглушка">
              <%end %>
              <div class="chat-info">
                <h3><%= friend.name %></h3>
                <% if friend.messages.any? %>
                  <% message_content = friend.messages.last.body %>
                <%else %>
                  <% message_content = "Нету сообщений" %>
                <%end %>
                <% if message_content.length > 25 %>
                  <% message_content = message_content.truncate(10) %>
                <% end %>
                <p><%= friend.name %> - <%= message_content %></p>
                <p class="room"><%= link_to "Перейти в комнату #{room.title}", room_link(room.title) %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <%else %>
      <div class="indent">
      <div class="text-center">
        <h3 class="my-auto">У вас пока нету друзей :(</h3>
      </div>
      </div>
    <% end %>
  </div>

  </body>
  </html>

<% else %>
  <div class="indent">
    <div class="text-center">
      <h3 class="my-auto">Вы не зарегистрированы</h3>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
 <div class="message">
    <p><%= message.user.name %> - <%= message.body %></p>
    <% if message.image? %>
      <%= image_tag message.image.thumb.url %>
    <% end %>
  </div>


app/views/rooms/_room.html.erb
<% link_to room.title, room_path(room.title), target: "_blank", rel: "noopener noreferrer" %>
<p><%= room.title %></p>

app/views/rooms/index.html.erb
<%= turbo_stream_from :rooms %>
<%= turbo_frame_tag :rooms do %>
    <%= render @rooms %>
  <%end %>

  <%if current_user %>
    <%= form_with model: @new_room do |f| %>
    <%= f.submit "New Room" %>
  <% end %>

  <% @rooms.each do |room| %>
    <p><%= link_to "Перейти в комнату #{room.title}", room_link(room.title) %></p>
  <% end %>

<% end %>

app/views/rooms/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Chat</title>
</head>
<body>

<div class="container">
  <%= turbo_stream_from @room %>

  <div class="chat-container">
    <div id="chat-messages" class="chat-messages">
      <%= turbo_frame_tag :messages do %>
        <% @messages.each do |message| %>
          <%= render partial: 'messages/message', locals: { message: message } %>
        <% end %>
      <% end %>
    </div>

    <%= form_with model: @new_message, html: {multipart: true}, id: "new_message_form", data: { controller: "message-form" } do |f| %>
      <%= f.text_field :body, autofocus: true, placeholder: "Your message", id: "message_body" %>
      <%= f.hidden_field :room_id, value: @room.id %>

      <div class="file-upload">
        <%= f.file_field :image, id: "upload-image" %>
        <label for="upload-image">
          <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Breezeicons-actions-22-mail-attachment.svg/2048px-Breezeicons-actions-22-mail-attachment.svg.png" class="paper_clip" height="30px" width="30px">
        </label>
      </div>
      <%= f.submit "Отправить", class: "btn_chat btn btn-secondary" %>
    <% end %>

  </div>
</div>

<script>
    document.addEventListener('turbo:submit-end', (event) => {
        const form = event.target;
        if (form && form.getAttribute('id') === 'new_message_form') {
            const formElement = document.getElementById('new_message_form');
            formElement.scrollIntoView({ behavior: 'smooth', block: 'end', inline: 'nearest' });

            document.getElementById('message_body').value = ''; // Очистить поле ввода после отправки сообщения
            document.getElementById('upload-image').value = null; // Очистить поле с изображением после отправки
        }
    });

    function scrollChatToBottom() {
        const chatMessages = document.getElementById('chat-messages');
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }

    scrollChatToBottom();

    document.addEventListener('turbo:submit-end', (event) => {
        const form = event.target;
        if (form && form.getAttribute('id') === 'new_message_form') {
            document.getElementById('message_body').value = ''; // Очистить поле ввода после отправки сообщения
        }
    });

</script>

</body>
</html>

app/views/users/edit.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :descriptions %>
    <%= f.text_area :descriptions, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %>
    <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary'%>
    или <%= link_to 'вернуться', :back %>
  </div>

  <div class="actions">
    <%= link_to 'Изменить пароль', edit_user_registration_path, class: 'btn btn-secondary' %>
  </div>

  <div class="actions">
    <%= link_to 'Выйти', logout_path, method: :delete, class: 'btn btn-danger'%>
  </div>
<% end %>

app/views/users/show.html.erb
<%if current_user %>
<!DOCTYPE html>
<html>
<body>

<main>
  <section class="user-profile">
    <% if current_user.present? && current_user.avatar.present? %>
      <%= image_tag current_user.avatar.url, alt: "Ваш аватар" %>
    <% else %>
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCSiylwVA6PW_GnlrPL-UmN7zPcmtnzPqXSVExvXbpPQ&s" alt="заглушка">
    <% end %>
    <h1><%= current_user.name %></h1>
    <p><%= current_user.descriptions %></p>
    <p>Друзей: <%= current_user.friends.count %></p>
    <%= link_to 'Редактировать профиль', edit_user_path(current_user), class: 'btn' %>
  </section>
</main>

</body>
</html>
<%end %>