config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'rooms/index'

  resources :rooms, only: [:create, :show], param: :title
  resources :messages, only: :create
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    delete '/logout', to: 'devise/sessions#destroy'
  end

  get 'friends/show'

  get 'users/:id', to: 'users#show', as: :user_profile

  root 'home#show'

  resources :friendships, only: [:create, :update, :destroy] do
    member do
      patch :accept
      patch :reject
    end
  end

  resource :user, only: [:edit, :update]

  get 'friendship_status', to: 'friendships#show', as: :friendship_status
  get 'friends', to: 'friends#show', as: :friend
  get 'friend_show', to: 'friends#index', as: :friend_show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :requester, class_name: 'User'
  belongs_to :requested, class_name: 'User'

  scope :pending_requests_for, ->(user) { where(requested_id: user.id, status: 'pending') }

  def create_room_for_friendship(user_id1, user_id2)
    room = Room.create(user_id: user_id1, title: "Room_#{SecureRandom.hex(3)}")
    room.users << [User.find(user_id1), User.find(user_id2)]
  end
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message, counter_cache: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  scope :sorted, ->  { order(:id)}

  validates :body, presence: true, unless: :image_attached?

  mount_uploader :image, ImageUploader

  def image_attached?
    self.image.present? && self.image.file.present?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, -> { sorted }, dependent: :destroy
  belongs_to :user
  before_create {self.title = SecureRandom.hex(3)}
  has_many :rooms_users
  has_many :users, through: :rooms_users
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requested_friendships, foreign_key: :requester_id, class_name: 'Friendship'
  has_many :received_friendships, foreign_key: :requested_id, class_name: 'Friendship'
  has_many :requested_friends, through: :requested_friendships, source: :requested
  has_many :received_friends, through: :received_friendships, source: :requester
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :rooms

  before_validation :set_default_name, on: :create

  validates :name, presence: true

  mount_uploader :avatar, AvatarUploader

  def pending_friend_requests
    Friendship.where(requested_id: id, status: 'pending')
  end

  def friends
    received_friends.where(friendships: { status: 'accepted' })
  end

  private

  def set_default_name
    self.name ||= "User-#{SecureRandom.hex(3)}"
  end


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def show
    @friend_requests = Friendship.pending_requests_for(current_user)
  end

  def index

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @rooms = Room.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @new_message = current_user.messages.build(strong_params)
    if @new_message.save
      @new_message.broadcast_append_to @new_message.room
    end
  end

  private

  def strong_params
    params.require(:message).permit(:room_id, :body, :image)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @new_room = Room.new
    @rooms = Room.all
  end

  def create
    @new_room = current_user&.rooms&.build
    if @new_room&.save
      @new_room.broadcast_append_to :rooms
    end
  end

  def show
    @room = Room.find_by!(title: params[:title])
    @messages = @room.messages
    @new_message = current_user&.messages&.build
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_user_path(@user), notice: 'Профиль успешно обновлен.'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :descriptions, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_link(title)
    request.protocol + request.host_with_port + "/rooms/#{title}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messager2</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<header>
  <nav>
    <ul>
      <% if current_user %>
        <li><%= link_to 'Главная', root_path(current_user) %></li>
        <li><%= link_to 'Профиль', user_profile_path(current_user) %></li>
        <li><%= link_to 'Найти Друзей', friendship_status_path(current_user) %></li>
        <li><%= link_to 'Друзья', friend_path(current_user) %></li>
      <% else %>
        <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
        <li><%= link_to 'Войти', new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

<%= yield %>
</body>
</html>